#!/usr/bin/env bash
set -euo pipefail

# set -x
# dependencies: go (duh), upx, sponge

for d in $(git ls-files | cut -d/ -f1 | sort -u); do

	pushd "$d" > /dev/null

	# `go build foo.go` will create a binary foo (instead of the package name)!
	go build -ldflags "-s -w"

	# --brute is usually overkill (think rust release mode)
	# command -v upx > /dev/null &&
	upx "$(basename "$PWD")" > /dev/null

	# stat --format='%n %s' "$(basename "$PWD")"
	du -csh "$(basename "$PWD")" | sponge > /dev/stdout | head -n1

	popd > /dev/null 2> /dev/null

	# TODO: link to ~/.local/bin

done
